# Generated by Django 5.1.15 on 2026-09-30 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('topic', models.CharField(blank=True, max_length=60)),
                ('message', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('admin_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['is_resolved', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text='mood, category or occasion', unique=True)),
                ('question', models.CharField(max_length=200)),
                ('options', models.JSONField(default=list)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StoreSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(default='Lumière & Co.', max_length=80)),
                ('support_email', models.EmailField(default='hello@lumiere.co.in', max_length=254)),
                ('support_phone', models.CharField(blank=True, max_length=20)),
                ('free_shipping_above', models.PositiveIntegerField(default=999)),
                ('shipping_fee', models.PositiveIntegerField(default=79)),
                ('cod_enabled', models.BooleanField(default=True)),
                ('cod_max_order', models.PositiveIntegerField(default=5000, help_text='COD hidden above this order total')),
                ('blocked_pincodes', models.TextField(blank=True, help_text="Pincodes or 3-digit prefixes you can't ship to, comma separated")),
                ('metro_prefixes', models.CharField(default='11,40,56,60,70,50,45', help_text='2-digit pincode prefixes with faster delivery', max_length=200)),
                ('metro_days', models.CharField(default='2-3', max_length=10)),
                ('standard_days', models.CharField(default='4-6', max_length=10)),
                ('low_stock_threshold', models.PositiveIntegerField(default=10)),
                ('unpaid_order_timeout_minutes', models.PositiveIntegerField(default=60, help_text='Unpaid online orders are cancelled and stock released after this')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'store settings',
                'verbose_name_plural': 'store settings',
            },
        ),
    ]
